dist: focal
language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    update: true

script:
  - mkdir build && cd build || exit
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build .

notifications:
  email:
    on_success: always
    on_failure: always
